

name: CI

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4

      - name: docker images
        run: |
            docker build -t ${{secrets.REGISTRY_USER}}/resume-update:${{github.run_number}} .
            docker build -t ${{secrets.REGISTRY_USER}}/resume-update .
      - name: push image
        run: |
          docker login -u ${{secrets.REGISTRY_USER}} -p ${{secrets.REGISTRY_PASS}}
          docker push ${{secrets.REGISTRY_USER}}/resume-update:${{github.run_number}} 
          docker push ${{secrets.REGISTRY_USER}}/resume-update

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
         # port: ${{ secrets.PORT }}
          script: |
                  docker rm -f resume-update
                  docker run -d --name resume-update -p 8080:5001 ${{secrets.REGISTRY_USER}}/resume-update:${{github.run_number}}

