

name: CI

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4

      - name: build images
        run: |
            docker build -t ${{secrets.REGISTRY_USER}}/resume-update:${{github.run_number}} .
            docker push ${{secrets.REGISTRY_USER}}/resume-update .
      - name: push image
        run: |
          docker login -u ${{secrets.REGISTRY_USER}} -p ${{secrets.REGISTRY_PASS}}
          docker push ${{secrets.REGISTRY_USER}}/resume-update:${{github.run_number}} 
          docker push ${{secrets.REGISTRY_USER}}/resume-update

