

name: CI

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4

      - name: docker images
        run: docker build -t kayitesimarieange3h/resume-update .

      - name: push image
        run: |
          docker login -u kayitesimarieange3h -p ${{secrets.REGISTRY_PASS}}
          docker push kayitesimarieange3h/resume-update
